app_name: utron chat application
base_url: http://localhost:8090
port: 8090
verbose: false
static_dir: public
view_dir: views
database: "postgres"
database_conn: "postgres://postgres@localhost/booking?sslmode=disable"
automigrate: true
no_model: false
